receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http: 
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
          - http://*
          - https://*

processors:
  batch:
  memory_limiter:
    limit_mib: 512
  resource:
    attributes:
    - key: service.instance.id
      value: ${HOSTNAME}
      action: insert
  attributes:
    actions:
    - key: environment  
      value: production
      action: insert

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  debug:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200

  prometheus:
    endpoint: 0.0.0.0:9090
    namespace: doc
    #const_labels:
      #env: doc
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679
    expvar:
      enabled: true

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, resource, attributes, batch ]
      exporters: [ otlp/jaeger, debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, resource, attributes, batch ]
      exporters: [ prometheus, debug ]
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, resource, attributes, batch ]
      exporters: [ otlphttp/logs, debug ]
