apiVersion: 1
datasources:
  
  #https://grafana.com/docs/grafana/latest/datasources/jaeger/
- name: Jaeger
  type: jaeger
  uid: c08e9569
  url: http://jaeger:16686
  isDefault: false
  jsonData:
    tracesToLogsV2:
      datasourceUid: f4f2436a
    tracesToMetrics:
      datasourceUid: 6f18c035

  #https://grafana.com/docs/grafana/latest/datasources/prometheus/
- name: Prometheus
  type: prometheus
  uid: 6f18c035
  url: http://prometheus:9090
  isDefault: true

  #https://grafana.com/docs/grafana/latest/datasources/loki/
- name: Loki
  type: loki
  uid: f4f2436a
  url: http://loki:3100
  isDefault: false

